name: IntelChat
version: 1.0
description: A more improved chat system!
authors: [oyasunadev, liam_allan, 1337]
website: http://dev.bukkit.org/server-mods/intelchat/
main: org.intelcraft.intelchat.IntelChat
commands:
    chat:
        description: Prefix for all the commands IntelChat includes.
        aliases: ch
        usage: /<command>